spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.nnvbxiykjfjnktpvyiog
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver