server:
  port: 7860

spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: development

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: classpath:certs/public.pem